### PR TITLE
Fixes related to /grants (scientific-python-hugo-theme#291)

### PR DESCRIPTION
**Pull request by alphapapa**
See <https://github.com/scientific-python/scientific-python-hugo-theme/issues/291>.

### CODE REVIEW

**Comment by alphapapa** [comment]
pre-commit.ci autofix

**Comment by alphapapa** [comment]
Note that the build and deployment are failing because the theme submodule needs to be updated as well.

**Comment by jarrodmillman** [comment]
I should checked more closely before merging https://github.com/scientific-python/scientific-python-hugo-theme/pull/292. I will revert it until we sort out how to handle this.

With this and theme update, I am seeing this on my local computer:
2023-10-17T18:13:48,767377539-07:00

Before it looked like:
2023-10-17T18:16:35,238872457-07:00

We may want to keep the grant styling specific to the grant boxes.

**Comment by jarrodmillman** [comment]
I reverted the theme changes here: https://github.com/scientific-python/scientific-python-hugo-theme/pull/294

This is just so the theme isn't broken until we figure out how to handle this.

**Pull request closed without merging**
