### PR TITLE
Delete poliastro.yaml

### PR DESCRIPTION
**Pull request by astrojuanlu**
See https://github.com/scientific-python/scientific-python.org/pull/271#issuecomment-1455082486

### CODE REVIEW

**Comment by astrojuanlu** [comment]
cc @jorgepiloto

**Review by tupui — COMMENTED** [review]
Thanks @astrojuanlu I think we also need to update the makefile. I can do that next week if you don't have time 😃

**Comment by astrojuanlu** [comment]
I knew I was missing something, thanks @tupui 🙏🏽

**Comment by tupui** [comment]
CI is happy, in it goes. Thanks, and I still hope to see you around from time to time 😊

**Pull request merged**
