### PR TITLE
Restyle SPEC table

### PR DESCRIPTION
**Pull request by stefanv**
image

Also hovers over table rows.

### CODE REVIEW

**Review by bsipocz — CHANGES_REQUESTED** [review]
I like the new styling, however, can we keep the text "DRAFT" where it's relevant though?

**Comment by stefanv** [comment]
I can put DRAFT back, although I'd like to change the definition. I think any project that has one endorsement should be taken out of DRAFT status.

**Comment by bsipocz** [comment]
> I can put DRAFT back, although I'd like to change the definition. I think any project that has one endorsement should be taken out of DRAFT status.

My concern is for the SPECs that are in the list, but are still without endorsements as they are still been worked on. However, we're also not exactly consistent on when something gets on the list, so maybe a solution is to not list them super early (OTOH, I would think it can have some value to list them when they are still in the active phrasing status).

**Comment by bsipocz** [comment]
(Now there are some new inconsistencies, SPEC 8 is already on the list on the website, but is missing from the rendering in this PR (while your screenshot lists both 7 and 8 in there, too))

**Comment by stefanv** [comment]
This is my local rendering:

image

I'm not sure what has/hasn't been pinned for scientific-python.org; SPEC 7 being missing isn't weird (that was only on my local branch), but SPEC 8 not being there is odd.

**Comment by stefanv** [comment]
> My concern is for the SPECs that are in the list, but are still without endorsements as they are still been worked on. However, we're also not exactly consistent on when something gets on the list, so maybe a solution is to not list them super early (OTOH, I would think it can have some value to list them when they are still in the active phrasing status).

I agree; we may want to consider making Draft an author-chosen status (`draft: true` in the pre-amble). This would be a signal to others that the document is *not ready for endorsement*. This is different from the document being *done* but *unendorsed*.

**Review by bsipocz — APPROVED** [review]
Looks great!

**Comment by bsipocz** [comment]
> I agree; we may want to consider making Draft an author-chosen status (draft: true in the pre-amble).

That would be great! I'll open a separate issue about it. I suppose I could try to do a PR, too, but it's likely will be a CSS disaster.

**Comment by stefanv** [comment]
Heh, no worries, it'll be a quick change :)

**Review by jarrodmillman — APPROVED** [review]

**Comment by jarrodmillman** [comment]
We should also port this to use the table from the theme.

**Pull request merged**
