### PR TITLE
Update subtitle and description

### PR DESCRIPTION
**Pull request by jarrodmillman**
We need a subtitle and description for the project.  Among other places, we will use these on our social media accounts.
For example, we are currently using this banner on our facebook account:
screenshot
I would also like to add a short description of the project to the facebook page.

# Subtitle

I would like to come up with a short subtitle for the Scientific Python project.  Currently we have are using "Ecosystem for scientific computing."  I would rather emphasize the community aspect and suggested "Community developed and owned".  Here are some other options (I prefer the first one, but the second one works for me as well).

- Community developed and owned
screenshot
- A community driven scientific ecosystem
screenshot
- A scientific computing ecosystem by the community, for the community
screenshot
- A community-developed ecosystem for scientific computing
screenshot
- A community ecosystem for scientific computing
screenshot

My preference for the first one is because I don't think we need to repeat the word scientific.  I also think at this point, most people are going to know that scientific Python is a collection of Python software packages for scientific computing.  But I suspect most people don't know to what extent it is community owned and developed.  I suspect many people think of open source and corporate control and manipulation as being closely connected (e.g., tensorflow).

# Description

I tried to use the phrase from the subtitle in the description to make it more clear what the subtitle meant, since I intended the subtitle to be a short phrase and not a sentence.

> 
> The Scientific Python **ecosystem** is a loose federation of **community**
> developed and owned Python projects widely used in scientific research, technical
> computing, and data science.
> 
> This website is part of the Scientific Python project, which aims to better
> coordinate the ecosystem and prepare Scientific Python for the next decade.

### CODE REVIEW

**Comment by stefanv** [comment]
Some of the other examples are from suggestions I made:

- Scientific Python: a scientific computing ecosystem by the community, for the community
- Scientific Python: a community driven scientific ecosystem
- Scientific Python: a community-developed ecosystem for scientific computing
- Scientific Python: a community ecosystem for scientific computing

I agree that it may not be necessary to repeat scientific, but I think "Scientific Python: community owned and developed" is a bit blunt, and fails to inform the user of what Scientific Python is.  So some mention of "ecosystem" or "computing" seems helpful there.

Maybe another one:

- Scientific Python: community owned computing

**Comment by jarrodmillman** [comment]
- Community owned ecosystem

I think 'community owned computing' sounds a bit like hardware.  I also started from trying to right a short sentence / description and then took words from it.  I don't know if it is helpful, but it may be useful.  At any rate, we need to draft a purpose / description / abstract for the project.  If we don't come up with a useful subtitle, we can just remove it.  But I think we do need an purpose / description / abstract statement.

**Comment by jarrodmillman** [comment]
Compare to https://deploy-preview-165--scientific-python-org.netlify.app/about/.

**Comment by stefanv** [comment]
Variant on Jarrod's, which somehow sounds quite nice to my ear:

"Community developed, community owned"

**Pull request merged**
