### PR TITLE
Change poliastro periodicity

### PR DESCRIPTION
**Pull request by astrojuanlu**
(Do not merge, still pending confirmation)

By the way, I guess it's not possible to specify "first Wednesday of every month"?

### CODE REVIEW

**Review by tupui — APPROVED** [review]

**Comment by tupui** [comment]
Ok I will wait for your signal 👍 

> By the way, I guess it's not possible to specify "first Wednesday of every month"?

It should be possible to do something like that as you can go crazy with the recurring rules. See: https://icalendar.org/iCalendar-RFC-5545/3-8-5-3-recurrence-rule.html
You could try to write the yml with the custom `RRULE` and locally create the ics to check it's valid.

**Review by jarrodmillman — APPROVED** [review]

**Comment by astrojuanlu** [comment]
Thanks @tupui! However it's not clear to me where could I write the `RRULE`, since `yaml2ics.py` builds the `rrule` according to a few fixed interval types:

https://github.com/scientific-python/yaml2ics/blob/caaa5b551a65cb8aafac7cb1778238f4c130d688/yaml2ics.py#L75-L80

Should I commit the `.ics` instead, open an issue in `yaml2ics`, or am I missing something?

**Comment by tupui** [comment]
Right, me might be missing something in yaml2ics 👍 

We don't yet have a way to only add the .ics. At the moment yml are parsed to generate ics and then these are added to the template. But we want to allow adding directly ics (or a link to an existing ics). If you are interested to work on this, that would be great 😃

**Comment by astrojuanlu** [comment]
I'd be happy to contribute on this area 😊 Maybe we can do it in 2 parts?

- Add a "scape hatch" to yaml2ics so that folks can specify the `rrule` of their liking in text form (should be easier, and would solve my use case)
- Add the possibility for projects to specify a URL with an ICS calendar directly instead of the YAML (more difficult, but would solve many projects use case, especially bigger ones with existing calendars)

How does that sound?

**Comment by tupui** [comment]
> I'd be happy to contribute on this area 😊 Maybe we can do it in 2 parts?

Yay thank you for helping us! Sorry I did not have time so far so that's great if you can help.

> * Add a "scape hatch" to yaml2ics so that folks can specify the `rrule` of their liking in text form (should be easier, and would solve my use case)
> * Add the possibility for projects to specify a URL with an ICS calendar directly instead of the YAML (more difficult, but would solve many projects use case, especially bigger ones with existing calendars)
> 
> How does that sound?

Sounds perfect and yes can be 2 PRs of course.

**Comment by stefanv** [comment]
My opinion: yes on custom rrules, maybe hold off on custom ics? This should solve the immediate problem without complicating our infrastructure.

**Comment by stefanv** [comment]
I see astropy and pandas all want custom ics, so looks like I should do it after all.

**Comment by tupui** [comment]
@astrojuanlu in case you missed this, we can now have custom RRULE thanks to https://github.com/scientific-python/yaml2ics/pull/41

**Comment by astrojuanlu** [comment]
Hi folks, sorry but I have reconsidered some of my priorities and as a result I [recently stepped down as poliastro maintainer](https://www.poliastro.space/blog/2022/12/21/juan-luis-steps-down/). The truth is that we haven't been having these community meetings for some time and probably the best course of action short term is for me to close this PR and instead delete the event until @jorgepiloto, who is now gradually taking over the package, decides what to do with them.

Thanks everyone for your patience 🙏🏽

**Pull request closed without merging**
