### PR TITLE
Add teams

### PR DESCRIPTION
**Pull request by stefanv**

### CODE REVIEW

**Comment by jarrodmillman** [comment]
I have a place for teams already and I need to update the team on the GH organization before we merge this.

**Comment by stefanv** [comment]
@jarrodmillman Feel free to repurpose this as necessary, or to push to this branch.

**Comment by jarrodmillman** [comment]
This is a note for myself to look at https://github.com/scientific-python/scientific-python-hugo-theme/pull/56.

**Comment by stefanv** [comment]
Looks good, thanks Jarrod.

**Pull request merged**
