### PR TITLE
Bot metric page. 

### PR DESCRIPTION
**Pull request by Carreau**
can't make it to work locally, testing netlify

### CODE REVIEW

**Comment by Carreau** [comment]
@stefanv, @jarrodmillman

**Comment by bsipocz** [comment]
Rendering seems to be off

Screenshot 2023-05-23 at 12 00 23

**Comment by Carreau** [comment]
You have an add blocker is my guess.

**Review by bsipocz — APPROVED** [review]
We agreed to move ahead with this as is, and fix any web design issues along with e.g. #396 (issues: adblocker should be worked around, heading sizes fixed, etc.)

**Comment by stefanv** [comment]
That's fine, but we should probably remove the top-level link to BOT for now.

**Comment by bsipocz** [comment]
> That's fine, but we should probably remove the top menu link to BOT for now.

I think that can happen while addressing https://github.com/scientific-python/scientific-python.org/issues/400

**Pull request merged**
