### PR TITLE
Create calendar for scipy-sparse-array.yaml

### PR DESCRIPTION
**Pull request by dschult**
Add biweekly meetings about scipy-sparse array followup from scientific python meeting

### CODE REVIEW

**Review by tupui — COMMENTED** [review]
Hey @dschult, thanks for that. The reason the CI is failing is because you also need to update the makefile so that it create the actual ics file from this config. Could you do that?

https://github.com/scientific-python/scientific-python.org/blob/fc030451c1c49a70fc3c5ccb9b739fdf313d2e8c/Makefile#L25

**Comment by dschult** [comment]
Thanks @tupui !!
I learned something today! :}

Let me know if spreading "calendars" over multiple lines like I did is not good style. I could use backslash if you prefer. The line was getting unreadable.

**Review by tupui — APPROVED** [review]
Great, thanks for the update 🚀 The output looks good and good rewrite of the makefile, thanks for that one too 😃

**Comment by stefanv** [comment]
Sorry for all that hassle; I've now simplified the process so the Makefile will pick up calendars automatically: https://github.com/scientific-python/scientific-python.org/pull/428

**Pull request merged**
