### PR TITLE
Update the time of the NumPy docs meeting

### PR DESCRIPTION
**Pull request by melissawm**
cc @InessaPawson

### CODE REVIEW

**Comment by melissawm** [comment]
Hi folks - it looks like the numpy.ics file hasn't changed after this PR, is this something to investigate or could it be just that it's taking longer than usual? I'd be happy to debug it if there is indeed a problem. Thanks! 😄

**Comment by InessaPawson** [comment]
I've resubscribed to the calendar. The issue is still present.

**Comment by tupui** [comment]
So actually on the PRs it's working just fine, but for some reason on main it was not rendered. Same thing happened for SunPy. The calendar command is just not running I think.

**Comment by tupui** [comment]
Oh or the website is just not build. Can you check on Netlify @stefanv or @jarrodmillman?

**Comment by stefanv** [comment]
I can verify that the website did not deploy; the build works fine locally, so I'll have to investigate what's going wrong.

**Comment by stefanv** [comment]
OK, should be updated now.

**Comment by tupui** [comment]
Thanks Stéfan! What was it? Anything we need to change here?

**Comment by stefanv** [comment]
The speed check plugin failed. We will have to investigate whether that is related to changes we made, or simply variance in the runtime environment.

**Comment by melissawm** [comment]
Thanks for investigating!

**Pull request merged**
