### PR TITLE
Update links for notes and meeting address

### PR DESCRIPTION
**Pull request by alexdesiqueira**
Links to meeting notes and address were outdated. Let's see if we can hold these ones for a while...

### CODE REVIEW

**Comment by stefanv** [comment]
Hey, Alex, happy to merge this. Putting m skimage hat on, question: why not stick with hack.md?

**Comment by alexdesiqueira** [comment]
Hey @stefanv,
in our meetings, four people can't be at the same document at once—hackmd gets very sluggish.
I suggested Etherpad since it's the "optimal" solution among the tools I've tested, it's FOSS and easy to use. Feel free to suggest alternatives if you'd like, though. Reminding also that that's a place for notes taken during the meeting, being transferred to their forever home at GH :slightly_smiling_face:

**Comment by stefanv** [comment]
That's odd. We've been using it for much larger meetings (numpy etc.) and never noticed speed issues.

Does etherpad now support Markdown? If so, I'm sure it's fine to use.

**Comment by alexdesiqueira** [comment]
I tried editing a document _alone_ right now. Things look fine, but if we have problems in the next meeting, I'll blame you both! :stuck_out_tongue_closed_eyes:

**Review by jarrodmillman — APPROVED** [review]

**Pull request merged**
