### PR TITLE
Get CC's frequency back to weekly

### PR DESCRIPTION
**Pull request by alexdesiqueira**
Now that we have a fixed address, let's get back to weekly meetings.

### CODE REVIEW

**Comment by tupui** [comment]
Just to be sure, the interval here is 14 and not 7.

**Comment by alexdesiqueira** [comment]
@tupui's axiom of non-weekness:
> "Two biweekly meetings won't make a weekly meeting"

:laughing: 

> Just to be sure, the interval here is 14 and not 7.

@tupui that's alright. Two biweekly meetings, one every week, one every other week :smile: Thanks for checking, though!

**Comment by tupui** [comment]
haha I missed that you had 2. Although looking at the calendar https://deploy-preview-309--scientific-python-org.netlify.app/calendars/ something seems to be off as both events are on the same week now.

**Comment by tupui** [comment]
LGTM now, meetings are indeed appearing every week :)

**Comment by alexdesiqueira** [comment]
Thanks @tupui! Appreciate it :slightly_smiling_face:

**Comment by tupui** [comment]
Pleasure

**Pull request merged**
