### PR TITLE
Added SciPy community calendar

### PR DESCRIPTION
**Pull request by melissawm**

### CODE REVIEW

**Comment by rossbar** [comment]
FWIW I clicked on the link for the `scipy.ics` calendar in the netlify preview then imported it in my google calendar, and it showed two scipy community events showing up every day, which was clearly not right. Is there a way to check that the calendars show up correctly when imported?

**Comment by melissawm** [comment]
Hm I might have done something wrong, this is the same issue as in #192

**Comment by melissawm** [comment]
@rossbar should be fixed now

**Review by rossbar — APPROVED** [review]
> should be fixed now

Can confirm - thanks @melissawm !

**Comment by stefanv** [comment]
Thanks @melissawm !

**Pull request merged**
