### PR TITLE
Sort SPEC endorsers

### PR DESCRIPTION
**Pull request by stefanv**

### CODE REVIEW

**Review by bsipocz — APPROVED** [review]

**Review by jarrodmillman — APPROVED** [review]

**Comment by jarrodmillman** [comment]
I am not sure this worked. See
2024-10-23T14:20:00,384109526-07:00
 ipython should be before scikit-image.

**Comment by bsipocz** [comment]
Ahh, but it works in the individual pages?
Screenshot 2024-10-23 at 14 31 18

**Comment by stefanv** [comment]
I didn't try to sort the icons... I could, though!

**Comment by jarrodmillman** [comment]
I was mainly interested in the icons b/c that is where you see the core project endorsements listed for all the SPECs. I occassionally look at that spec table to see if I can identify what projects haven't endorsed which specs. So it helps me if they are sorted on that page. I don't have a use-case for sorting them on individual cases, but we should probably sort them there as well.

**Comment by stefanv** [comment]
Icon sorting added.

**Comment by bsipocz** [comment]
This works now as expected, thank you Stefan!

Screenshot 2024-10-30 at 12 42 37

**Review by bsipocz — APPROVED** [review]

**Pull request merged**
