### PR TITLE
MAINT: do not add red TODO text to rendered webpage

### PR DESCRIPTION
**Pull request by bsipocz**
IMO we should open issues for TODO items instead of rendering them out to the webpage.

### CODE REVIEW

**Comment by stefanv** [comment]
We were hoping to have these knocked out by SciPy, but fine to have them commented out :)

**Comment by stefanv** [comment]
I found a great way to allow these changes, without users complaining:

image

**Comment by bsipocz** [comment]
Oh, that's the type I had in mind :) Fortunately I don't think I have a backup of the eyesore, yet hardly any information websites I had back in those days unfortunately meaning that the wonderful gifs are lost, too.

**Comment by tupui** [comment]
Apple style when they make a Keynote. They have so much money they can take the whole store out for a day!

**Pull request merged**
