### PR TITLE
Remove GitHub pages push functionality

### PR DESCRIPTION
**Pull request by stefanv**
Deployment will soon happen via Netlify.

### CODE REVIEW

**Comment by jarrodmillman** [comment]
Will we be able to delay deploying to netlify after we merge to main?  We are using that now and I am not sure we are ready to have anything merged to main deployed.

**Comment by jarrodmillman** [comment]
Also could we have netlify deploy to something like:  preview.scientific-python.org?

I can't remember the current address and have to keep looking it up.

**Comment by stefanv** [comment]
Yes, we can delay.  If I deploy to preview.scientific-python.org I guess it becomes a non-issue, so will set that up now.

**Comment by stefanv** [comment]
OK, I moved `draft.scientific-python.org` to `specs.scientific-python.org` and set up `preview.scientific-python.org` for the main repo.

**Comment by jarrodmillman** [comment]
See #180

**Pull request closed without merging**
