### PR TITLE
add mpl calendar

### PR DESCRIPTION
**Pull request by tacaswell**
Add the Matplotlib weekly call to the calenders.

I also updated the docs and the make file based on what I had to do to get the
website to build locally.

### CODE REVIEW

**Comment by tacaswell** [comment]
I cherry-picked the commit from #212 to get the new Hugo version.

**Comment by stefanv** [comment]
Thank you @tacaswell!  Those Makefile changes look correct for the latest version of Hugo.  At some point we should update the Makefile to just glob all ics files @jarrodmillman @tupui

**Review by stefanv — APPROVED** [review]

**Comment by tacaswell** [comment]
well, cherry-picking @jarrodmillman 's commit made it worse...

**Comment by tacaswell** [comment]
Should I force-push that out of existence or back away and let y'all deal with this?

**Comment by stefanv** [comment]
Don't worry about it, we'll get this working.

**Review by jarrodmillman — APPROVED** [review]

**Pull request merged**
