### PR TITLE
Twitter

### PR DESCRIPTION
**Pull request by jarrodmillman**
@stefanv Could you confirm that we don't use the widget stuff that I removed in 54e5083.

### CODE REVIEW

**Comment by stefanv** [comment]
The social media widgets are still supported by the theme, so you can use them if you want to.

**Comment by stefanv** [comment]
Here's what it currently does in `footer.html`:

```
{{- $socialMedia := index $footer "socialmedia" }}

              {{- range $socialMedia }}
              <a class="level-item" href="{{ .link }}" aria-label="{{ .link }}">
                <span class="icon"><i class="fab fa-{{ .icon }}"></i></span>
              </a>
              {{- end }}
```

**Comment by jarrodmillman** [comment]
The stuff you mention from the `footer.html` looks like it refers to this section from the config:
```
      socialmedia:
      - link: https://github.com/scientific-python/
        icon: github
      - link: https://www.youtube.com/channel/UC2wKi87Wmy9C1OQMyD9fGxA
        icon: youtube
      - link: https://facebook.com/scientific.python
        icon: facebook
      - link: https://twitter.com/scientific_py
        icon: twitter
```
In 54e5083, I remove this section
```
  widgets:
    social:
      github: scientific-python
      custom:
        - title: Youtube
          url: 'https://www.youtube.com/channel/UC2wKi87Wmy9C1OQMyD9fGxA'
```

I can't see any visual difference in the website with the widgets section present.  The social media icons still appear and work when I remove the widgets section:
screenshot

**Comment by stefanv** [comment]
Looks like the data actually comes from `footer -> socialmedia`, not from widgets.

**Comment by stefanv** [comment]
(I.e., widgets can be dropped.)

**Comment by stefanv** [comment]
I see you wrote the same above :+1:

**Pull request merged**
