### PR TITLE
add Data Umbrella: Polars event

### PR DESCRIPTION
**Pull request by reshamas**
cc: @stefanv

### CODE REVIEW

**Comment by stefanv** [comment]
Thanks @reshamas! The preview looks good.

**Review by stefanv — APPROVED** [review]

**Review by jarrodmillman — APPROVED** [review]

**Comment by stefanv** [comment]
🎉 https://scientific-python.org/calendars/ — I'm subscribing :)

**Comment by stefanv** [comment]
@reshamas BTW, the calendar entry here is for one hour, but the one sent by the event platform is for 2 1/2.

**Comment by reshamas** [comment]
> @reshamas BTW, the calendar entry here is for one hour, but the one sent by the event platform is for 2 1/2.

It should be 1 hour (sometimes the webinar runs a bit over, so we add a buffer). I've updated the BigMarker link. Thank you.

**Pull request merged**
